### ISSUE TITLE
About STOP-LIMIT feature

### ISSUE THREAD

**Issue by gaorufeng** [ohenrik/bitfinex#11]
Maybe the Bitfinex api V2 support  STOP-LIMIT feature, how can i use restv2 ( STOP-LIMIT) for bitfinex.com.

**Comment by gaorufeng** [comment]
Cannot call authenticate() on unestablished connection!
Cannot call subscribe_to_candles() on unestablished connection!
Cannot call new_order() on unestablished connection!

import os
key = os.environ.get("my key")
secret = os.environ.get("my secret")
from bitfinex.websockets import BtfxWss
bm = BtfxWss(key, secret)

# Authenticate and listen to account feedback
# print is the callback method. You probably want to do something else.
bm.authenticate(print)

# Subscribe to candles (starts with a set of completed candles, then updates with last completed + updated uncompleted candle)
bm.subscribe_to_candles("EOSUSD", "1m", print)
bm.start()

# Send new order
bm.new_order(order_type="LIMIT", pair="EOSUSD", amount="5", price="4", hidden=0)

**Comment by ohenrik** [comment]
Are you sure the key and secret are correct and working?

Also Are you waiting with executing the new_order command until after the connection is live?

If you run the code above as is, the new_order command might not work because the connection has not been able to Authenticate yet.

**Comment by gaorufeng** [comment]
@dantimofte  @ohenrik  By the way, Python wss_example.py for Linux is OK, but in the Windows10, error
Python3.6
python -m  venv . (pytest1)
pip3 install git+https://github.com/ohenrik/bitfinex.git  (that's ok)
C:\pytest1\Scripts\activate.bat

(pytest1) C:\pytest1>python wss_example.py

###############START##############
Traceback (most recent call last):
  File "wss_example.py", line 112, in <module>
    MYOBJ = MyWssTest()
  File "wss_example.py", line 30, in __init__
    self.mywss.authenticate(self.cb_auth)
  File "C:\pytest1\lib\site-packages\bitfinex\websockets\client.py", line 166, in authenticate
    nonce = int(wss_utils.UtcNow() * 1000000)
  File "C:\pytest1\lib\site-packages\bitfinex\websockets\wss_utils.py", line 6, in UtcNow
    return int(float(now.strftime("%s.%f"))*10000000)
ValueError: Invalid format string

**Comment by dantimofte** [comment]
> @dantimofte @ohenrik Thank you very much for your help. They work normally.
> 
> The exch_order = self.mywss.new_order("LIMIT", "tEOSUSD", "5", "4") is OK! Great!
> 
> I hope to use "STOP LIMIT", I checked it out the Bitfinex's Websocket API 2.0 version , (price_aux_limit decimal Auxiliary Limit price (for STOP LIMIT))
> 
> It looks like 2 prices are needed
> 
> I tried it.
> 
> ("STOP LIMIT", "tEOSUSD", "5", "4","0",{"PRICE_AUX_LIMIT":"4.1"})
> 
> ("STOP LIMIT", "tEOSUSD", "5", "4","0","4.1")
> 
> /client.py", line 308, in new_order_op flags": sum(flags)
> TypeError: unsupported operand type(s) for +: 'int' and 'str'

Indeed you can't place a stop limit order via websocket. Please open another issue and ask for this as a feature

**Comment by gaorufeng** [comment]
> > @dantimofte @ohenrik Thank you very much for your help. They work normally.
> > The exch_order = self.mywss.new_order("LIMIT", "tEOSUSD", "5", "4") is OK! Great!
> > I hope to use "STOP LIMIT", I checked it out the Bitfinex's Websocket API 2.0 version , (price_aux_limit decimal Auxiliary Limit price (for STOP LIMIT))
> > It looks like 2 prices are needed
> > I tried it.
> > ("STOP LIMIT", "tEOSUSD", "5", "4","0",{"PRICE_AUX_LIMIT":"4.1"})
> > ("STOP LIMIT", "tEOSUSD", "5", "4","0","4.1")
> > /client.py", line 308, in new_order_op flags": sum(flags)
> > TypeError: unsupported operand type(s) for +: 'int' and 'str'
> 
> Indeed you can't place a stop limit order via websocket. Please open another issue and ask for this as a feature

OK,Thanks
